# Generated by Django 5.2.3 on 2025-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_response_information_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='area_affected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area affected in square kilometers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='infrastructure_damage',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('catastrophic', 'Catastrophic')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='people_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disasterreport',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
